### ISSUE TITLE
High queue churn leads to high memory usage

### ISSUE THREAD

**Issue by spatula75** [rabbitmq/rabbitmq-management#166]
The backstory can be found in [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/VeeTjmSS9OA).

With 3.6.2 Milestone 2 (but not with 3.5.7) we have observed that the amount of memory in use by the stats collector grows without bound until a resource alarm gets raised by the stats collector node.  This appears to be happening when many queues come and go (e.g., short-lived reply queues), though the nominal number of active connections, queues and channels remains quite low (less than 10 connections and less than 100 each of queues and channels).

We're running RabbitMQ in a three-node cluster with a very rudimentary configuration, using nearly all default values.  For reference, our configuration and the output of rabbitmqctl report are attached (with some light editing to protect the innocent).  It's plausible that the same would happen in a single-node configuration, but we haven't tested this.

Also attached is a short Ruby script that connects, then goes into a loop in which it opens a channel, creates 500 exclusive, auto-delete queues with consumers, waits 11 seconds (to make sure the queues are around long enough to emit stats), cancels all the consumers, deletes all the queues, then closes the channel.  (These queues are bound to an exchange which periodically (once a minute) receives a short message from a separate server process, though this is plausibly not relevant to the problem.)

In our environment, the stats collector will grow in size by about 90 MB per hour while this script runs.  Forcibly running garbage collection with `rabbitmqctl eval '[garbage_collect(P) || P <- processes()].' ` has no effect.  Stopping the script does not result in the freeing of (much) memory.

The general impression this gives is that old stats for deleted queues are somehow not getting aggregated or perhaps purged, though I'm sure there are other possible explanations (like maybe aggregation defaults changing or being ignored, etc).  We have at least verified that we're not somehow leaking queues or channels.

[rmq.zip](https://github.com/rabbitmq/rabbitmq-management/files/201078/rmq.zip)

We're happy to try to help if there are more data we can gather or test builds to try.

**Comment by spatula75** [comment]
FWIW, nothing new in the SASL log or anything non-routine (AMQP connects/disconnects) in the regular log file during the running of this script.

**Comment by michaelklishin** [comment]
Thank you. For how long do you run the test script?

**Comment by spatula75** [comment]
I ran it for four hours while I went out to get lunch and run some errands and saw about 360MB of increase, though the increase is more or less linear with respect to time-- we will start seeing usage inch up right away.  (As you would expect, there's some increase and decrease over time, but the overall trend is a slow overall increase.)

**Comment by spatula75** [comment]
Also I apologize in advance if my Ruby is an eyesore.  I'm not a native Ruby speaker.

**Comment by spatula75** [comment]
Additional testing seems to indicate that explicitly configuring retention periods has set an upper bound on the amount that the memory consumption will increase, though it isn't clear whether it was the act of setting explicit limits or setting them to lower-than-normal durations that changed the behavior.  It's still considerably more than 3.5.7 uses, but at least it keeps the size bounded well below the point at which it would trigger a resource alarm (so far).

**Comment by michaelklishin** [comment]
It makes sense than lowering retention periods helps. What values did you
use?

On Sun, Apr 3, 2016 at 8:18 PM, Nicklas Johnson <notifications@github.com>
wrote:

> Additional testing seems to indicate that explicitly configuring retention
> periods has set an upper bound on the amount that the memory consumption
> will increase, though it isn't clear whether it was the act of setting
> explicit limits or setting them to lower-than-normal durations that changed
> the behavior. It's still considerably more than 3.5.7 uses, but at least it
> keeps the size bounded well below the point at which it would trigger a
> resource alarm (so far).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rabbitmq/rabbitmq-management/issues/166#issuecomment-205013878>
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by spatula75** [comment]
I only changed the values for global:
`{global, [{605,5}, {3660, 60}, {11400 , 600}, {23400 ,1800}]}`
And explicitly configured the others to the defaults.

However now I'm seeing minimal, bounded bloat when explicitly configuring the defaults for global as well.  I'm going to let this run a while longer before trying to draw any conclusion based on that though.

**Comment by spatula75** [comment]
I just noticed I also changed rates_mode to 'none' from 'basic' as well, so after this runs for a bit, I'll switch that back to determine which thing made the difference.  Probably would have been better for me to change just one thing at a time.

**Comment by michaelklishin** [comment]
Changing rates_mode will also affect the total amount of data collected.

**Comment by spatula75** [comment]
It looks like it's actually the rates_mode switch that stopped the unbound growth.  Setting it to "none" stops it; setting it back to "basic" returns us to seemingly unbound growth in memory usage.  Given that we were OK on 3.5.7, my guess is that something changed with either the storage, aggregation or purging of historical rate data, or the data used to compute the rates later, with respect to queues which have been deleted.

**Comment by michaelklishin** [comment]
@dcorbacho can you please investigate what can be improved here?

**Comment by dcorbacho** [comment]
The memory increase seems to be caused by an internal index in the new management stats, which is not properly garbage collected. I'm verifying it and will soon provide a patch if that is the problem.

However, it must be noted that the memory will always slightly increase until it keeps enough history for the given intervals.

**Comment by spatula75** [comment]
Sure, we expect that to analyze the data it is necessary to collect the data and keep it somewhere.  Growing memory usage is totally fine and expected, so long as it has some (rough) upper boundary based on the aggregation/purging of old data.

**Comment by dcorbacho** [comment]
I have a fix for the indexes that will PR tomorrow, but the memory is still increasing and it is not being consumed in the management plugin.

I'm getting this memory usage (in MB) at the beginning of the test:

```
[{total,113.359696},
 {connection_readers,0.065856},
 {connection_writers,0.00144},
 {connection_channels,0.379688},
 {connection_other,0.276192},
 {queue_procs,8.77924},
 {queue_slave_procs,0.0},
 {plugins,2.402888},
 {other_proc,17.394368},
 {mnesia,1.091296},
 {mgmt_db,5.082736},
 {msg_index,21.57156},
 {other_ets,10.228192},
 {binary,2.251904},
 {code,31.041474},
 {atom,1.484937},
 {other_system,11.307925}]
```
and now:
```
[{total,268.885224},
 {connection_readers,0.045168},
 {connection_writers,0.00144}, {connection_channels,0.444464},
 {connection_other,0.158808}, {queue_procs,8.581632},
 {queue_slave_procs,0.0},
 {plugins,1.0},
 {other_proc,125.075192},
 {mnesia,1.091232}, {mgmt_db,4.644296},
 {msg_index,54.538848},
 {other_ets,16.475744},
 {binary,1.258456},
 {code,31.22285},
 {atom,1.910993},
 {other_system,22.436101}]
```
`other_proc` and `msg_index` are taking a good chunk of memory, so I will investigate if that is normal. It might be possible that some processes in the `mgmt_db` are not properly accounted for and end up in `other_proc`.

**Comment by michaelklishin** [comment]
@spatula75 we believe this is fixed. Can you please email me what package you'd like for testing?

**Comment by spatula75** [comment]
Awesome, email sent.

**Comment by spatula75** [comment]
Still seeing linear growth with respect to time in our stage environment.  Our longest retention period is 6.5 hours, so I would have expected it to have leveled off about 6 hours ago.

The breakdown currently looks like this: 

224kB	mnesia
8.1MB	message store index
212MB	management database
9.5MB	other

Will continue to keep an eye on it today to see if it eventually does level off.

**Comment by spatula75** [comment]
Interestingly, running the test script against our QA server is not revealing the same issue, so I wonder if there may be multiple issues at play.  I will continue keeping an eye on it and trying to duplicate what I'm seeing with an easily run script.

**Comment by spatula75** [comment]
@michaelklishin @dcorbacho,

It seems like there's still a slow leak.  I've augmented the test script (and made it uglier in the process) to more accurately simulate the kind of traffic we produce and attached it to the bottom of this comment.

I started by configuring the retention times so that nothing is retained past 3660s.

Then I ran two instances of this script simultaneously.  The memory grew slowly and steadily, some of which you'd expect by virtue of having an active system.

Then I stopped the scripts when about 200MB was in use, waited for all of the stats retention times to pass, ran garbage collection manually several times, and still had about 170 MB in use.

The major differences between the first script and this one is that this one has much more channel churn,  multiple connections, and it also has two consumers on a queue that is very long-lived, which is more like our actual workload.  I also added a publish with a routing key that nothing would be listening for, which is something that can happen in our environment.

I'm afraid I don't have a particularly great working hypothesis, but it seems a bit like having many publishes to long-lived queues mattered.  If you'd prefer, I can move this to a new & different issue since we're no longer talking about queue churn as such (that specific problem seems to indeed be fixed).

[simload.zip](https://github.com/rabbitmq/rabbitmq-management/files/207738/simload.zip)

**Comment by dcorbacho** [comment]
Thanks @spatula75, I'll try it out

**Comment by dcorbacho** [comment]
I can confirm that the issue can be reproduced with the new script in the `stable` branch. It took the system a few hours to ramp up the memory, but I have now 300MB of management data.

@spatula75 could you please open a different issue for the follow up? Thanks

**Comment by michaelklishin** [comment]
@dcorbacho I just did: https://github.com/rabbitmq/rabbitmq-management/issues/173.
